# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# loom is unstable
org.gradle.daemon=false

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.20.4
	loader_version=0.15.9

# Mod Properties
	mod_version = 1.20.4-7.0.0
	maven_group = com.andrews.table_top_craft
	archives_base_name = table_top_craft

# Dependencies
	fabric_version = 0.97.0+1.20.4
	mod_menu_version = 9.0.0
	sodium_version = mc1.20.4-0.5.8
	iris_version = 1.6.17+1.20.4