## Gradle Stuff
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment Properties
forge_version=47.1.47
forge_version_range=[46.0.0,)
loader_version_range=[46,)
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties
mod_version=1.20.1-6.1.2
mod_id=table_top_craft
mod_name=Table Top Craft
mod_license=LGPLv3
mod_group_id=com.andrews.table_top_craft
mod_authors=andrew0030
mod_description=Table Top Craft is a Mod that adds playable table top games to Minecraft.

## Links
display_url=https://www.curseforge.com/minecraft/mc-mods/table-top-craft
issue_tracker_url=https://github.com/andrew0030/Table-Top-Craft/issues