package moe.plushie.table_top_craft.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.client.renderer.GlStateManager;
import org.lwjgl.opengl.GL11;

/**
 * ChessKnight - andrew0030
 * Created using Tabula 7.0.0
 */
public class ChessKnight extends ModelBase {
    public ModelRenderer HorseBody;
    public ModelRenderer Base;
    public ModelRenderer HorseLegTopFrontRight;
    public ModelRenderer HorseLegTopFrontLeft;
    public ModelRenderer HorseSaddleBase;
    public ModelRenderer HorseTailTop;
    public ModelRenderer HorseNeck;
    public ModelRenderer HorseLegTopBackRight;
    public ModelRenderer HorseLegTopBackRight_1;
    public ModelRenderer HorseLegMidFrontRight;
    public ModelRenderer HorseLegLowerFrontRight;
    public ModelRenderer HorseLegMidFrontLeft;
    public ModelRenderer HorseLegLowerFrontLeft;
    public ModelRenderer HorseSaddleDetailBack;
    public ModelRenderer HorseSaddleDetailFront;
    public ModelRenderer HorseSaddleRopeLeft;
    public ModelRenderer HorseSaddleRopeRight;
    public ModelRenderer HorseSaddleGripLeft;
    public ModelRenderer HorseSaddleGripRight;
    public ModelRenderer HorseTailMid;
    public ModelRenderer HorseTailLower;
    public ModelRenderer HorseHair;
    public ModelRenderer HorseHead;
    public ModelRenderer HorseFaceTop;
    public ModelRenderer HorseFaceLower;
    public ModelRenderer HorseFaceDetailLeft;
    public ModelRenderer HorseFaceDetailRight;
    public ModelRenderer HorseEarLeft;
    public ModelRenderer HorseEarRight;
    public ModelRenderer HorseLegMidBackLeft;
    public ModelRenderer HorseLegLowerBackLeft;
    public ModelRenderer HorseLegMidBackRight;
    public ModelRenderer HorseLegLowerBackRight;
    public ModelRenderer HumanUpperBody;
    public ModelRenderer HumanLowerBody;
    public ModelRenderer Head;
    public ModelRenderer HumanUpperArmRight;
    public ModelRenderer HumanUpperArmLeft;
    public ModelRenderer HumanUpperLegLeft;
    public ModelRenderer HumanUpperLegRight;
    public ModelRenderer HumanLowerLegLeft;
    public ModelRenderer HumanLowerLegRight;
    public ModelRenderer HumanUpperArmRight_1;
    public ModelRenderer WeaponGrip;
    public ModelRenderer WeaponMidPart;
    public ModelRenderer WeaponBlade;
    public ModelRenderer WeaponBladeTop;
    public ModelRenderer WeaponBladeBack;
    public ModelRenderer WeaponBladeFront;
    public ModelRenderer HumanUpperArmLeft_1;

    public ChessKnight() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.HumanUpperArmLeft = new ModelRenderer(this, 0, 83);
        this.HumanUpperArmLeft.setRotationPoint(3.0F, 2.0F, 0.0F);
        this.HumanUpperArmLeft.addBox(0.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmLeft, -1.3658946726107624F, 0.31869712141416456F, -1.4114477660878142F);
        this.HumanLowerLegRight = new ModelRenderer(this, 9, 76);
        this.HumanLowerLegRight.setRotationPoint(-1.0F, 4.0F, -1.0F);
        this.HumanLowerLegRight.addBox(-1.0F, 0.0F, 0.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanLowerLegRight, 1.0821041362364843F, 0.0F, 0.0F);
        this.HorseSaddleDetailFront = new ModelRenderer(this, 106, 9);
        this.HorseSaddleDetailFront.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseSaddleDetailFront.addBox(-1.5F, -1.0F, -3.0F, 3, 1, 2, 0.0F);
        this.HorseNeck = new ModelRenderer(this, 0, 12);
        this.HorseNeck.setRotationPoint(0.0F, -3.0F, -16.0F);
        this.HorseNeck.addBox(-2.05F, -9.8F, -2.0F, 4, 14, 7, 0.0F);
        this.setRotateAngle(HorseNeck, 0.9560913642424937F, 0.0F, 0.0F);
        this.WeaponBladeTop = new ModelRenderer(this, 0, 102);
        this.WeaponBladeTop.setRotationPoint(0.0F, -0.4F, 0.0F);
        this.WeaponBladeTop.addBox(0.0F, 0.0F, 0.0F, 1, 2, 2, 0.0F);
        this.setRotateAngle(WeaponBladeTop, -0.7853981633974483F, 0.0F, 0.0F);
        this.HorseLegLowerFrontLeft = new ModelRenderer(this, 44, 51);
        this.HorseLegLowerFrontLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseLegLowerFrontLeft.addBox(-2.4F, 5.1F, -2.1F, 4, 3, 4, 0.0F);
        this.HorseLegMidBackRight = new ModelRenderer(this, 96, 43);
        this.HorseLegMidBackRight.setRotationPoint(0.0F, 6.0F, 0.0F);
        this.HorseLegMidBackRight.addBox(-1.0F, 0.0F, -1.5F, 3, 5, 3, 0.0F);
        this.setRotateAngle(HorseLegMidBackRight, 0.5061454830783556F, 0.0F, 0.0F);
        this.HumanUpperArmRight = new ModelRenderer(this, 9, 83);
        this.HumanUpperArmRight.setRotationPoint(-2.0F, 1.0F, -1.0F);
        this.HumanUpperArmRight.addBox(-2.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmRight, -1.593485607070823F, 0.36425021489121656F, 0.31869712141416456F);
        this.HumanUpperArmRight_1 = new ModelRenderer(this, 9, 90);
        this.HumanUpperArmRight_1.setRotationPoint(-1.0F, 4.0F, 1.0F);
        this.HumanUpperArmRight_1.addBox(-1.0F, 0.0F, -2.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmRight_1, -0.36425021489121656F, 0.0F, 0.0F);
        this.HumanUpperLegRight = new ModelRenderer(this, 9, 69);
        this.HumanUpperLegRight.setRotationPoint(-1.0F, 3.0F, -1.0F);
        this.HumanUpperLegRight.addBox(-2.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperLegRight, -1.0471975511965976F, 0.6283185307179586F, 0.0F);
        this.HorseTailLower = new ModelRenderer(this, 24, 3);
        this.HorseTailLower.setRotationPoint(0.0F, 1.0F, 0.0F);
        this.HorseTailLower.addBox(-1.5F, -4.5F, 9.0F, 3, 4, 5, 0.0F);
        this.setRotateAngle(HorseTailLower, -0.13962634015954636F, 0.0F, 0.0F);
        this.HorseLegLowerBackRight = new ModelRenderer(this, 96, 51);
        this.HorseLegLowerBackRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseLegLowerBackRight.addBox(-1.5F, 5.1F, -2.0F, 4, 3, 4, 0.0F);
        this.HorseSaddleGripLeft = new ModelRenderer(this, 74, 0);
        this.HorseSaddleGripLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseSaddleGripLeft.addBox(-0.5F, 6.0F, -1.0F, 1, 2, 2, 0.0F);
        this.HorseLegMidFrontRight = new ModelRenderer(this, 60, 41);
        this.HorseLegMidFrontRight.setRotationPoint(0.0F, 6.0F, -0.5F);
        this.HorseLegMidFrontRight.addBox(-1.1F, 0.0F, -1.6F, 3, 5, 3, 0.0F);
        this.setRotateAngle(HorseLegMidFrontRight, 0.6373942428283291F, 0.0F, 0.0F);
        this.HumanUpperLegLeft = new ModelRenderer(this, 0, 69);
        this.HumanUpperLegLeft.setRotationPoint(1.0F, 3.0F, -1.0F);
        this.HumanUpperLegLeft.addBox(0.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperLegLeft, -1.0471975511965976F, -0.6283185307179586F, 0.0F);
        this.HumanUpperArmLeft_1 = new ModelRenderer(this, 0, 90);
        this.HumanUpperArmLeft_1.setRotationPoint(1.0F, 4.0F, 1.0F);
        this.HumanUpperArmLeft_1.addBox(-1.0F, 0.0F, -2.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmLeft_1, -0.5462880558742251F, 0.0F, 0.0F);
        this.HumanLowerLegLeft = new ModelRenderer(this, 0, 76);
        this.HumanLowerLegLeft.setRotationPoint(1.0F, 4.0F, -1.0F);
        this.HumanLowerLegLeft.addBox(-1.0F, 0.0F, 0.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanLowerLegLeft, 1.0821041362364843F, 0.0F, 0.0F);
        this.HorseTailTop = new ModelRenderer(this, 44, 0);
        this.HorseTailTop.setRotationPoint(0.0F, -7.0F, 5.5F);
        this.HorseTailTop.addBox(-1.0F, -1.0F, 0.0F, 2, 2, 3, 0.0F);
        this.setRotateAngle(HorseTailTop, -0.9105382707654417F, 0.0F, 0.0F);
        this.WeaponBladeFront = new ModelRenderer(this, 13, 112);
        this.WeaponBladeFront.setRotationPoint(0.0F, 2.0F, 2.0F);
        this.WeaponBladeFront.addBox(0.0F, -1.0F, 0.0F, 1, 1, 5, 0.0F);
        this.setRotateAngle(WeaponBladeFront, 0.9075712110370513F, 0.0F, 0.0F);
        this.HorseFaceTop = new ModelRenderer(this, 24, 18);
        this.HorseFaceTop.setRotationPoint(0.0F, 0.02F, 0.02F);
        this.HorseFaceTop.addBox(-2.0F, -10.0F, -7.0F, 4, 3, 6, 0.0F);
        this.Head = new ModelRenderer(this, 0, 47);
        this.Head.setRotationPoint(0.0F, 0.0F, -1.0F);
        this.Head.addBox(-2.0F, -4.0F, -2.0F, 4, 4, 4, 0.0F);
        this.setRotateAngle(Head, 0.04363323129985824F, 0.0F, 0.0F);
        this.HorseEarRight = new ModelRenderer(this, 0, 0);
        this.HorseEarRight.setRotationPoint(0.0F, -0.5F, 0.0F);
        this.HorseEarRight.addBox(-2.45F, -12.0F, 4.0F, 2, 3, 1, 0.0F);
        this.HumanUpperBody = new ModelRenderer(this, 0, 34);
        this.HumanUpperBody.setRotationPoint(8.0F, -22.0F, 15.0F);
        this.HumanUpperBody.addBox(-2.0F, 0.0F, -2.0F, 4, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperBody, 0.045553093477052F, 0.0F, 0.0F);
        this.HorseLegTopFrontRight = new ModelRenderer(this, 60, 29);
        this.HorseLegTopFrontRight.setRotationPoint(-4.0F, -2.0F, -17.0F);
        this.HorseLegTopFrontRight.addBox(-1.1F, -1.0F, -2.1F, 3, 8, 4, 0.0F);
        this.setRotateAngle(HorseLegTopFrontRight, -0.6829473363053812F, 0.0F, 0.0F);
        this.WeaponBladeBack = new ModelRenderer(this, 0, 112);
        this.WeaponBladeBack.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.WeaponBladeBack.addBox(0.0F, 0.0F, 0.0F, 1, 1, 5, 0.0F);
        this.setRotateAngle(WeaponBladeBack, 0.6806784082777886F, 0.0F, 0.0F);
        this.WeaponMidPart = new ModelRenderer(this, 9, 97);
        this.WeaponMidPart.setRotationPoint(-0.5F, -1.0F, -1.0F);
        this.WeaponMidPart.addBox(0.0F, 0.0F, 0.0F, 2, 3, 1, 0.0F);
        this.HorseLegLowerFrontRight = new ModelRenderer(this, 60, 51);
        this.HorseLegLowerFrontRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseLegLowerFrontRight.addBox(-1.6F, 5.1F, -2.1F, 4, 3, 4, 0.0F);
        this.HorseSaddleDetailBack = new ModelRenderer(this, 80, 9);
        this.HorseSaddleDetailBack.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseSaddleDetailBack.addBox(-4.0F, -1.0F, 3.0F, 8, 1, 2, 0.0F);
        this.WeaponBlade = new ModelRenderer(this, 0, 102);
        this.WeaponBlade.setRotationPoint(0.5F, 0.5F, -7.0F);
        this.WeaponBlade.addBox(0.0F, 0.0F, 0.0F, 1, 2, 7, 0.0F);
        this.HorseLegMidBackLeft = new ModelRenderer(this, 78, 43);
        this.HorseLegMidBackLeft.setRotationPoint(0.0F, 6.0F, 0.0F);
        this.HorseLegMidBackLeft.addBox(-2.0F, 0.0F, -1.5F, 3, 5, 3, 0.0F);
        this.setRotateAngle(HorseLegMidBackLeft, 0.5061454830783556F, 0.0F, 0.0F);
        this.HorseFaceLower = new ModelRenderer(this, 24, 27);
        this.HorseFaceLower.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseFaceLower.addBox(-2.0F, -7.0F, -6.5F, 4, 2, 5, 0.0F);
        this.HorseLegMidFrontLeft = new ModelRenderer(this, 44, 41);
        this.HorseLegMidFrontLeft.setRotationPoint(0.0F, 6.0F, -0.5F);
        this.HorseLegMidFrontLeft.addBox(-1.9F, 0.0F, -1.6F, 3, 5, 3, 0.0F);
        this.setRotateAngle(HorseLegMidFrontLeft, 0.8651597102135892F, 0.0F, 0.0F);
        this.HorseLegTopFrontLeft = new ModelRenderer(this, 44, 29);
        this.HorseLegTopFrontLeft.setRotationPoint(4.0F, -2.0F, -17.0F);
        this.HorseLegTopFrontLeft.addBox(-1.9F, -1.0F, -2.1F, 3, 8, 4, 0.0F);
        this.setRotateAngle(HorseLegTopFrontLeft, -0.40980330836826856F, 0.0F, 0.0F);
        this.HorseSaddleRopeLeft = new ModelRenderer(this, 70, 0);
        this.HorseSaddleRopeLeft.setRotationPoint(5.0F, 1.0F, 0.0F);
        this.HorseSaddleRopeLeft.addBox(-0.5F, 0.0F, -0.5F, 1, 6, 1, 0.0F);
        this.HorseSaddleGripRight = new ModelRenderer(this, 74, 4);
        this.HorseSaddleGripRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseSaddleGripRight.addBox(-0.5F, 6.0F, -1.0F, 1, 2, 2, 0.0F);
        this.WeaponGrip = new ModelRenderer(this, 0, 97);
        this.WeaponGrip.setRotationPoint(-0.5F, 2.5F, -2.5F);
        this.WeaponGrip.addBox(0.0F, 0.0F, 0.0F, 1, 1, 3, 0.0F);
        this.HorseHead = new ModelRenderer(this, 0, 0);
        this.HorseHead.setRotationPoint(0.0F, -4.5F, -0.5F);
        this.HorseHead.addBox(-2.5F, -10.0F, -1.5F, 5, 5, 7, 0.0F);
        this.HorseEarLeft = new ModelRenderer(this, 0, 0);
        this.HorseEarLeft.setRotationPoint(0.0F, -0.5F, 0.0F);
        this.HorseEarLeft.addBox(0.45F, -12.0F, 4.0F, 2, 3, 1, 0.0F);
        this.HorseLegLowerBackLeft = new ModelRenderer(this, 78, 51);
        this.HorseLegLowerBackLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseLegLowerBackLeft.addBox(-2.5F, 5.1F, -2.0F, 4, 3, 4, 0.0F);
        this.HorseLegTopBackRight_1 = new ModelRenderer(this, 96, 29);
        this.HorseLegTopBackRight_1.setRotationPoint(-4.0F, -2.0F, 2.0F);
        this.HorseLegTopBackRight_1.addBox(-1.5F, -2.0F, -2.5F, 4, 9, 5, 0.0F);
        this.setRotateAngle(HorseLegTopBackRight_1, 0.17453292519943295F, 0.0F, 0.0F);
        this.HorseFaceDetailLeft = new ModelRenderer(this, 74, 13);
        this.HorseFaceDetailLeft.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseFaceDetailLeft.addBox(1.5F, -8.0F, -4.0F, 1, 2, 2, 0.0F);
        this.HorseHair = new ModelRenderer(this, 58, 0);
        this.HorseHair.setRotationPoint(0.0F, -3.0F, -2.0F);
        this.HorseHair.addBox(-1.0F, -11.5F, 5.0F, 2, 16, 4, 0.0F);
        this.HumanLowerBody = new ModelRenderer(this, 0, 41);
        this.HumanLowerBody.setRotationPoint(0.0F, 4.0F, 0.0F);
        this.HumanLowerBody.addBox(-2.0F, 0.0F, -2.0F, 4, 3, 2, 0.0F);
        this.setRotateAngle(HumanLowerBody, -0.22759093446006054F, 0.0F, 0.0F);
        this.HorseSaddleBase = new ModelRenderer(this, 80, 0);
        this.HorseSaddleBase.setRotationPoint(0.0F, -9.0F, -7.0F);
        this.HorseSaddleBase.addBox(-5.0F, 0.0F, -3.0F, 10, 1, 8, 0.0F);
        this.HorseTailMid = new ModelRenderer(this, 38, 7);
        this.HorseTailMid.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseTailMid.addBox(-1.5F, -2.0F, 3.0F, 3, 4, 7, 0.0F);
        this.setRotateAngle(HorseTailMid, -0.091106186954104F, 0.0F, 0.0F);
        this.HorseFaceDetailRight = new ModelRenderer(this, 74, 13);
        this.HorseFaceDetailRight.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.HorseFaceDetailRight.addBox(-2.5F, -8.0F, -4.0F, 1, 2, 2, 0.0F);
        this.HorseSaddleRopeRight = new ModelRenderer(this, 80, 0);
        this.HorseSaddleRopeRight.setRotationPoint(-5.0F, 1.0F, 0.0F);
        this.HorseSaddleRopeRight.addBox(-0.5F, 0.0F, -0.5F, 1, 6, 1, 0.0F);
        this.Base = new ModelRenderer(this, 0, 0);
        this.Base.setRotationPoint(0.2F, 0.0F, 0.2F);
        this.Base.addBox(0.0F, 0.0F, 0.0F, 16, 3, 16, 0.0F);
        this.HorseLegTopBackRight = new ModelRenderer(this, 78, 29);
        this.HorseLegTopBackRight.setRotationPoint(4.0F, -2.0F, 2.0F);
        this.HorseLegTopBackRight.addBox(-2.5F, -2.0F, -2.5F, 4, 9, 5, 0.0F);
        this.setRotateAngle(HorseLegTopBackRight, 0.17453292519943295F, 0.0F, 0.0F);
        this.HorseBody = new ModelRenderer(this, 0, 34);
        this.HorseBody.setRotationPoint(1.0F, -0.8F, 1.4F);
        this.HorseBody.addBox(-5.0F, -8.0F, -19.0F, 10, 10, 24, 0.0F);
        this.setRotateAngle(HorseBody, -0.6981317007977318F, 0.0F, 0.0F);
        this.HumanUpperBody.addChild(this.HumanUpperArmLeft);
        this.HumanUpperLegRight.addChild(this.HumanLowerLegRight);
        this.HorseSaddleBase.addChild(this.HorseSaddleDetailFront);
        this.HorseBody.addChild(this.HorseNeck);
        this.WeaponBlade.addChild(this.WeaponBladeTop);
        this.HorseLegMidFrontLeft.addChild(this.HorseLegLowerFrontLeft);
        this.HorseLegTopBackRight_1.addChild(this.HorseLegMidBackRight);
        this.HumanUpperBody.addChild(this.HumanUpperArmRight);
        this.HumanUpperArmRight.addChild(this.HumanUpperArmRight_1);
        this.HumanLowerBody.addChild(this.HumanUpperLegRight);
        this.HorseTailMid.addChild(this.HorseTailLower);
        this.HorseLegMidBackRight.addChild(this.HorseLegLowerBackRight);
        this.HorseSaddleRopeLeft.addChild(this.HorseSaddleGripLeft);
        this.HorseLegTopFrontRight.addChild(this.HorseLegMidFrontRight);
        this.HumanLowerBody.addChild(this.HumanUpperLegLeft);
        this.HumanUpperArmLeft.addChild(this.HumanUpperArmLeft_1);
        this.HumanUpperLegLeft.addChild(this.HumanLowerLegLeft);
        this.HorseBody.addChild(this.HorseTailTop);
        this.WeaponBladeTop.addChild(this.WeaponBladeFront);
        this.HorseHead.addChild(this.HorseFaceTop);
        this.HumanUpperBody.addChild(this.Head);
        this.HorseHead.addChild(this.HorseEarRight);
        this.Base.addChild(this.HumanUpperBody);
        this.HorseBody.addChild(this.HorseLegTopFrontRight);
        this.WeaponBladeTop.addChild(this.WeaponBladeBack);
        this.WeaponGrip.addChild(this.WeaponMidPart);
        this.HorseLegMidFrontRight.addChild(this.HorseLegLowerFrontRight);
        this.HorseSaddleBase.addChild(this.HorseSaddleDetailBack);
        this.WeaponMidPart.addChild(this.WeaponBlade);
        this.HorseLegTopBackRight.addChild(this.HorseLegMidBackLeft);
        this.HorseHead.addChild(this.HorseFaceLower);
        this.HorseLegTopFrontLeft.addChild(this.HorseLegMidFrontLeft);
        this.HorseBody.addChild(this.HorseLegTopFrontLeft);
        this.HorseSaddleBase.addChild(this.HorseSaddleRopeLeft);
        this.HorseSaddleRopeRight.addChild(this.HorseSaddleGripRight);
        this.HumanUpperArmRight_1.addChild(this.WeaponGrip);
        this.HorseNeck.addChild(this.HorseHead);
        this.HorseHead.addChild(this.HorseEarLeft);
        this.HorseLegMidBackLeft.addChild(this.HorseLegLowerBackLeft);
        this.HorseBody.addChild(this.HorseLegTopBackRight_1);
        this.HorseHead.addChild(this.HorseFaceDetailLeft);
        this.HorseNeck.addChild(this.HorseHair);
        this.HumanUpperBody.addChild(this.HumanLowerBody);
        this.HorseBody.addChild(this.HorseSaddleBase);
        this.HorseTailTop.addChild(this.HorseTailMid);
        this.HorseHead.addChild(this.HorseFaceDetailRight);
        this.HorseSaddleBase.addChild(this.HorseSaddleRopeRight);
        this.HorseBody.addChild(this.HorseLegTopBackRight);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) { 
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.Base.offsetX, this.Base.offsetY, this.Base.offsetZ);
        GlStateManager.translate(this.Base.rotationPointX * f5, this.Base.rotationPointY * f5, this.Base.rotationPointZ * f5);
        GlStateManager.scale(0.1D, 0.1D, 0.1D);
        GlStateManager.translate(-this.Base.offsetX, -this.Base.offsetY, -this.Base.offsetZ);
        GlStateManager.translate(-this.Base.rotationPointX * f5, -this.Base.rotationPointY * f5, -this.Base.rotationPointZ * f5);
        this.Base.render(f5);
        GlStateManager.popMatrix();
        GlStateManager.pushMatrix();
        GlStateManager.translate(this.HorseBody.offsetX, this.HorseBody.offsetY, this.HorseBody.offsetZ);
        GlStateManager.translate(this.HorseBody.rotationPointX * f5, this.HorseBody.rotationPointY * f5, this.HorseBody.rotationPointZ * f5);
        GlStateManager.scale(0.06D, 0.06D, 0.06D);
        GlStateManager.translate(-this.HorseBody.offsetX, -this.HorseBody.offsetY, -this.HorseBody.offsetZ);
        GlStateManager.translate(-this.HorseBody.rotationPointX * f5, -this.HorseBody.rotationPointY * f5, -this.HorseBody.rotationPointZ * f5);
        this.HorseBody.render(f5);
        GlStateManager.popMatrix();
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
