package andrews.table_top_craft.tile_entities.model.chess;

import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class ChessKingModel
{
    public ModelRenderer Base;
    public ModelRenderer ChairBase;
    public ModelRenderer HumanUpperBody;
    public ModelRenderer ChairRoundBottomRight;
    public ModelRenderer ChairRoundBottomLeft;
    public ModelRenderer ChairBack;
    public ModelRenderer ChairArmPartRight;
    public ModelRenderer ChairArmPartLeft;
    public ModelRenderer ChairFootHolder;
    public ModelRenderer ChairRoundMidRight;
    public ModelRenderer Spike;
    public ModelRenderer Spike_1;
    public ModelRenderer ChairRoundTopRight;
    public ModelRenderer Spike_2;
    public ModelRenderer Spike_3;
    public ModelRenderer ChairRoundTop;
    public ModelRenderer Spike_4;
    public ModelRenderer Spike_5;
    public ModelRenderer Spike_6;
    public ModelRenderer ChairRoundMidLeft;
    public ModelRenderer Spike_7;
    public ModelRenderer Spike_8;
    public ModelRenderer ChairRoundTopLeft;
    public ModelRenderer Spike_9;
    public ModelRenderer Spike_10;
    public ModelRenderer Spike_11;
    public ModelRenderer ChairBackRight;
    public ModelRenderer ChairBackRight_1;
    public ModelRenderer ChairBackTop;
    public ModelRenderer ChairArmPartFrontRight;
    public ModelRenderer ChairSupportRight;
    public ModelRenderer ChairSupportRight_1;
    public ModelRenderer WeaponGrip;
    public ModelRenderer WeaponHandProtection;
    public ModelRenderer WeaponBlade;
    public ModelRenderer WeaponTop;
    public ModelRenderer WeaponBladeRight;
    public ModelRenderer WeaponBladeLeft;
    public ModelRenderer ChairArmPartFrontLeft;
    public ModelRenderer ChairSupportLeft;
    public ModelRenderer ChairSupportLeft_1;
    public ModelRenderer CrownMain;
    public ModelRenderer CrownRightSpike;
    public ModelRenderer CrownMidSpike;
    public ModelRenderer CrownLeftSpike;
    public ModelRenderer CrownGem;
    public ModelRenderer CrownGem_1;
    public ModelRenderer CrownGem_2;
    public ModelRenderer HumanLowerBody;
    public ModelRenderer Head;
    public ModelRenderer HumanUpperArmRight;
    public ModelRenderer HumanUpperArmLeft;
    public ModelRenderer HumanUpperLegLeft;
    public ModelRenderer HumanUpperLegRight;
    public ModelRenderer HumanLowerLegLeft;
    public ModelRenderer HumanLowerLegRight;
    public ModelRenderer CrownFront;
    public ModelRenderer CrownRight;
    public ModelRenderer CrownLeft;
    public ModelRenderer CrownBack;
    public ModelRenderer CrownSpike;
    public ModelRenderer CrownSpike_1;
    public ModelRenderer CrownSpike_2;
    public ModelRenderer CrownSpike_3;
    public ModelRenderer CrownSpike_4;
    public ModelRenderer CrownSpike_5;
    public ModelRenderer CrownSpike_6;
    public ModelRenderer CrownSpike_7;
    public ModelRenderer HumanUpperArmRight_1;
    public ModelRenderer HumanUpperArmLeft_1;

    public ChessKingModel()
    {
    	int[] textureSize = {128, 128};
        this.CrownLeftSpike = new ModelRenderer(textureSize[0], textureSize[1], 79, 19);
        this.CrownLeftSpike.setRotationPoint(0.0F, -2.0F, 0.0F);
        this.CrownLeftSpike.addBox(0.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
        this.ChairBase = new ModelRenderer(textureSize[0], textureSize[1], 0, 20);
        this.ChairBase.setRotationPoint(-5.0F, -3.0F, -3.0F);
        this.ChairBase.addBox(0.0F, 0.0F, 0.0F, 10, 3, 8, 0.0F);
        this.HumanUpperBody = new ModelRenderer(textureSize[0], textureSize[1], 50, 50);
        this.HumanUpperBody.setRotationPoint(0.0F, -11.5F, 1.0F);
        this.HumanUpperBody.addBox(-2.0F, 0.0F, -2.0F, 4, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperBody, 0.017453292519943295F, 0.0F, 0.0F);
        this.WeaponBlade = new ModelRenderer(textureSize[0], textureSize[1], 26, 37);
        this.WeaponBlade.setRotationPoint(0.5F, 1.0F, 0.5F);
        this.WeaponBlade.addBox(0.0F, 0.0F, 0.0F, 2, 8, 1, 0.0F);
        this.CrownSpike_1 = new ModelRenderer(textureSize[0], textureSize[1], 0, 3);
        this.CrownSpike_1.setRotationPoint(4.0F, -1.0F, 0.0F);
        this.CrownSpike_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.Spike_1 = new ModelRenderer(textureSize[0], textureSize[1], 7, 101);
        this.Spike_1.setRotationPoint(-0.5F, 7.0F, -1.5F);
        this.Spike_1.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.WeaponBladeRight = new ModelRenderer(textureSize[0], textureSize[1], 33, 32);
        this.WeaponBladeRight.setRotationPoint(0.0F, 2.0F, 0.0F);
        this.WeaponBladeRight.addBox(-1.0F, 0.0F, 0.0F, 1, 7, 1, 0.0F);
        this.setRotateAngle(WeaponBladeRight, 0.0F, 0.0F, 2.4172810140121466F);
        this.CrownMain = new ModelRenderer(textureSize[0], textureSize[1], 65, 14);
        this.CrownMain.setRotationPoint(1.5F, -12.8F, 9.4F);
        this.CrownMain.addBox(0.0F, 0.0F, 0.0F, 7, 3, 1, 0.0F);
        this.HumanUpperLegLeft = new ModelRenderer(textureSize[0], textureSize[1], 57, 63);
        this.HumanUpperLegLeft.setRotationPoint(0.5F, 3.5F, -1.0F);
        this.HumanUpperLegLeft.addBox(0.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperLegLeft, -1.2217304763960306F, -0.3490658503988659F, 0.0F);
        this.CrownBack = new ModelRenderer(textureSize[0], textureSize[1], 0, 122);
        this.CrownBack.setRotationPoint(1.0F, 0.0F, 4.0F);
        this.CrownBack.addBox(0.0F, 0.0F, 0.0F, 3, 2, 1, 0.0F);
        this.CrownSpike_2 = new ModelRenderer(textureSize[0], textureSize[1], 5, 0);
        this.CrownSpike_2.setRotationPoint(2.0F, -1.0F, 0.0F);
        this.CrownSpike_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.CrownGem_2 = new ModelRenderer(textureSize[0], textureSize[1], 47, 29);
        this.CrownGem_2.setRotationPoint(-4.0F, 2.7F, 0.3F);
        this.CrownGem_2.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.setRotateAngle(CrownGem_2, 0.0F, 0.0F, 0.7853981633974483F);
        this.ChairBackTop = new ModelRenderer(textureSize[0], textureSize[1], 14, 56);
        this.ChairBackTop.setRotationPoint(1.0F, -18.0F, -1.0F);
        this.ChairBackTop.addBox(0.0F, 0.0F, 0.0F, 8, 1, 1, 0.0F);
        this.HumanLowerLegRight = new ModelRenderer(textureSize[0], textureSize[1], 48, 70);
        this.HumanLowerLegRight.setRotationPoint(-1.0F, 4.0F, -1.0F);
        this.HumanLowerLegRight.addBox(-1.0F, 0.0F, 0.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanLowerLegRight, 1.3089969389957472F, 0.0F, 0.0F);
        this.CrownSpike_7 = new ModelRenderer(textureSize[0], textureSize[1], 10, 3);
        this.CrownSpike_7.setRotationPoint(2.0F, -1.0F, 4.0F);
        this.CrownSpike_7.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.ChairSupportLeft = new ModelRenderer(textureSize[0], textureSize[1], 51, 20);
        this.ChairSupportLeft.setRotationPoint(-1.0F, 0.7F, 0.0F);
        this.ChairSupportLeft.addBox(-1.0F, 0.0F, 0.0F, 2, 7, 1, 0.0F);
        this.setRotateAngle(ChairSupportLeft, 0.0F, 0.0F, -0.2617993877991494F);
        this.CrownSpike = new ModelRenderer(textureSize[0], textureSize[1], 10, 6);
        this.CrownSpike.setRotationPoint(0.0F, -1.0F, 0.0F);
        this.CrownSpike.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.ChairArmPartFrontLeft = new ModelRenderer(textureSize[0], textureSize[1], 66, 0);
        this.ChairArmPartFrontLeft.setRotationPoint(-1.0F, 1.0F, -1.0F);
        this.ChairArmPartFrontLeft.addBox(0.0F, 0.0F, 0.0F, 1, 6, 7, 0.0F);
        this.CrownGem = new ModelRenderer(textureSize[0], textureSize[1], 37, 29);
        this.CrownGem.setRotationPoint(1.0F, 2.7F, 0.3F);
        this.CrownGem.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.setRotateAngle(CrownGem, 0.0F, 0.0F, 0.7853981633974483F);
        this.HumanUpperLegRight = new ModelRenderer(textureSize[0], textureSize[1], 48, 63);
        this.HumanUpperLegRight.setRotationPoint(-0.5F, 3.5F, -1.0F);
        this.HumanUpperLegRight.addBox(-2.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperLegRight, -1.2217304763960306F, 0.3490658503988659F, 0.0F);
        this.ChairRoundBottomLeft = new ModelRenderer(textureSize[0], textureSize[1], 9, 69);
        this.ChairRoundBottomLeft.setRotationPoint(10.0F, 1.5F, 8.0F);
        this.ChairRoundBottomLeft.addBox(0.0F, 0.0F, -2.0F, 2, 10, 2, 0.0F);
        this.setRotateAngle(ChairRoundBottomLeft, 0.0F, 0.0F, -2.792526803190927F);
        this.Spike_6 = new ModelRenderer(textureSize[0], textureSize[1], 42, 101);
        this.Spike_6.setRotationPoint(-0.15F, 5.0F, -1.5F);
        this.Spike_6.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(Spike_6, 0.0F, 0.0F, 0.4363323129985824F);
        this.HumanUpperArmLeft = new ModelRenderer(textureSize[0], textureSize[1], 63, 50);
        this.HumanUpperArmLeft.setRotationPoint(2.0F, 0.5F, -1.0F);
        this.HumanUpperArmLeft.addBox(0.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmLeft, -0.3490658503988659F, 0.0F, -0.3490658503988659F);
        this.ChairRoundTopLeft = new ModelRenderer(textureSize[0], textureSize[1], 9, 92);
        this.ChairRoundTopLeft.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.ChairRoundTopLeft.addBox(0.0F, 0.0F, -2.0F, 2, 6, 2, 0.0F);
        this.setRotateAngle(ChairRoundTopLeft, 0.0F, 0.0F, -0.4886921905584123F);
        this.ChairSupportRight_1 = new ModelRenderer(textureSize[0], textureSize[1], 44, 20);
        this.ChairSupportRight_1.setRotationPoint(0.0F, 0.7F, 4.0F);
        this.ChairSupportRight_1.addBox(-1.0F, 0.0F, 0.0F, 2, 7, 1, 0.0F);
        this.setRotateAngle(ChairSupportRight_1, -0.016950223790720947F, 0.0F, 0.2617993877991494F);
        this.CrownMidSpike = new ModelRenderer(textureSize[0], textureSize[1], 72, 19);
        this.CrownMidSpike.setRotationPoint(2.5F, -2.0F, 0.0F);
        this.CrownMidSpike.addBox(0.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
        this.Spike_10 = new ModelRenderer(textureSize[0], textureSize[1], 56, 101);
        this.Spike_10.setRotationPoint(-1.5F, 5.8F, -1.5F);
        this.Spike_10.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.HumanLowerLegLeft = new ModelRenderer(textureSize[0], textureSize[1], 57, 70);
        this.HumanLowerLegLeft.setRotationPoint(1.0F, 4.0F, -1.0F);
        this.HumanLowerLegLeft.addBox(-1.0F, 0.0F, 0.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanLowerLegLeft, 1.3089969389957472F, 0.0F, 0.0F);
        this.ChairSupportRight = new ModelRenderer(textureSize[0], textureSize[1], 37, 20);
        this.ChairSupportRight.setRotationPoint(0.0F, 0.7F, 0.0F);
        this.ChairSupportRight.addBox(-1.0F, 0.0F, 0.0F, 2, 7, 1, 0.0F);
        this.setRotateAngle(ChairSupportRight, 0.0F, 0.0F, 0.2617993877991494F);
        this.HumanUpperArmRight_1 = new ModelRenderer(textureSize[0], textureSize[1], 41, 57);
        this.HumanUpperArmRight_1.setRotationPoint(-1.0F, 4.0F, 1.0F);
        this.HumanUpperArmRight_1.addBox(-1.0F, 0.0F, -2.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmRight_1, -1.0471975511965976F, 0.0F, 0.0F);
        this.CrownFront = new ModelRenderer(textureSize[0], textureSize[1], 0, 104);
        this.CrownFront.setRotationPoint(-2.5F, -5.3F, -2.5F);
        this.CrownFront.addBox(0.0F, 0.0F, 0.0F, 5, 2, 1, 0.0F);
        this.Spike_9 = new ModelRenderer(textureSize[0], textureSize[1], 63, 101);
        this.Spike_9.setRotationPoint(-1.5F, 1.5F, -1.5F);
        this.Spike_9.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.ChairBack = new ModelRenderer(textureSize[0], textureSize[1], 0, 37);
        this.ChairBack.setRotationPoint(0.0F, 0.0F, 7.5F);
        this.ChairBack.addBox(0.0F, -17.0F, -1.0F, 10, 17, 1, 0.0F);
        this.Spike_11 = new ModelRenderer(textureSize[0], textureSize[1], 49, 101);
        this.Spike_11.setRotationPoint(-1.5F, 2.7F, -1.5F);
        this.Spike_11.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.WeaponHandProtection = new ModelRenderer(textureSize[0], textureSize[1], 33, 41);
        this.WeaponHandProtection.setRotationPoint(-1.0F, 3.0F, -1.5F);
        this.WeaponHandProtection.addBox(0.0F, 0.0F, 0.0F, 3, 1, 2, 0.0F);
        this.ChairBackRight = new ModelRenderer(textureSize[0], textureSize[1], 7, 56);
        this.ChairBackRight.setRotationPoint(-1.9F, -15.0F, -1.0F);
        this.ChairBackRight.addBox(0.0F, 0.0F, 0.0F, 2, 11, 1, 0.0F);
        this.ChairRoundBottomRight = new ModelRenderer(textureSize[0], textureSize[1], 0, 69);
        this.ChairRoundBottomRight.setRotationPoint(0.0F, 1.5F, 8.0F);
        this.ChairRoundBottomRight.addBox(-2.0F, 0.0F, -2.0F, 2, 10, 2, 0.0F);
        this.setRotateAngle(ChairRoundBottomRight, 0.0F, 0.0F, 2.792526803190927F);
        this.ChairArmPartLeft = new ModelRenderer(textureSize[0], textureSize[1], 98, 2);
        this.ChairArmPartLeft.setRotationPoint(11.0F, -4.0F, 0.0F);
        this.ChairArmPartLeft.addBox(-2.0F, 0.0F, -2.0F, 3, 1, 8, 0.0F);
        this.CrownRight = new ModelRenderer(textureSize[0], textureSize[1], 0, 108);
        this.CrownRight.setRotationPoint(0.0F, 0.0F, 1.0F);
        this.CrownRight.addBox(0.0F, 0.0F, 0.0F, 1, 2, 4, 0.0F);
        this.WeaponGrip = new ModelRenderer(textureSize[0], textureSize[1], 27, 32);
        this.WeaponGrip.setRotationPoint(-1.0F, -6.4F, -0.7F);
        this.WeaponGrip.addBox(0.0F, 0.0F, -1.0F, 1, 3, 1, 0.0F);
        this.setRotateAngle(WeaponGrip, -0.19198621771937624F, 0.0F, 0.0F);
        this.HumanUpperArmLeft_1 = new ModelRenderer(textureSize[0], textureSize[1], 63, 57);
        this.HumanUpperArmLeft_1.setRotationPoint(1.0F, 4.0F, 1.0F);
        this.HumanUpperArmLeft_1.addBox(-1.0F, 0.0F, -2.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmLeft_1, -1.0471975511965976F, 0.0F, 0.0F);
        this.ChairRoundMidRight = new ModelRenderer(textureSize[0], textureSize[1], 0, 82);
        this.ChairRoundMidRight.setRotationPoint(0.0F, 10.0F, 0.0F);
        this.ChairRoundMidRight.addBox(-2.0F, 0.0F, -2.0F, 2, 7, 2, 0.0F);
        this.setRotateAngle(ChairRoundMidRight, 0.0F, 0.0F, 0.5235987755982988F);
        this.Spike = new ModelRenderer(textureSize[0], textureSize[1], 0, 101);
        this.Spike.setRotationPoint(-0.5F, 2.5F, -1.5F);
        this.Spike.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.Base = new ModelRenderer(textureSize[0], textureSize[1], 0, 0);
        this.Base.setRotationPoint(0.0F, 21.0F, 0.0F);
        this.Base.addBox(-8.0F, 0.0F, -8.0F, 16, 3, 16, 0.0F);
        this.Head = new ModelRenderer(textureSize[0], textureSize[1], 50, 41);
        this.Head.setRotationPoint(0.0F, 0.0F, -1.0F);
        this.Head.addBox(-2.0F, -4.0F, -2.0F, 4, 4, 4, 0.0F);
        this.ChairArmPartRight = new ModelRenderer(textureSize[0], textureSize[1], 83, 0);
        this.ChairArmPartRight.setRotationPoint(0.0F, -4.0F, 0.0F);
        this.ChairArmPartRight.addBox(-2.0F, 0.0F, -2.0F, 3, 1, 8, 0.0F);
        this.CrownGem_1 = new ModelRenderer(textureSize[0], textureSize[1], 42, 29);
        this.CrownGem_1.setRotationPoint(-1.5F, 2.7F, 0.3F);
        this.CrownGem_1.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.setRotateAngle(CrownGem_1, 0.0F, 0.0F, 0.7853981633974483F);
        this.CrownRightSpike = new ModelRenderer(textureSize[0], textureSize[1], 65, 19);
        this.CrownRightSpike.setRotationPoint(5.0F, -2.0F, 0.0F);
        this.CrownRightSpike.addBox(0.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
        this.ChairSupportLeft_1 = new ModelRenderer(textureSize[0], textureSize[1], 58, 20);
        this.ChairSupportLeft_1.setRotationPoint(-1.0F, 0.7F, 4.0F);
        this.ChairSupportLeft_1.addBox(-1.0F, 0.0F, 0.0F, 2, 7, 1, 0.0F);
        this.setRotateAngle(ChairSupportLeft_1, 0.0F, 0.0F, -0.2617993877991494F);
        this.CrownSpike_4 = new ModelRenderer(textureSize[0], textureSize[1], 5, 6);
        this.CrownSpike_4.setRotationPoint(4.0F, -1.0F, 2.0F);
        this.CrownSpike_4.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.ChairRoundTop = new ModelRenderer(textureSize[0], textureSize[1], 18, 91);
        this.ChairRoundTop.setRotationPoint(0.0F, 6.0F, 0.0F);
        this.ChairRoundTop.addBox(-2.0F, 0.0F, -2.0F, 2, 7, 2, 0.0F);
        this.setRotateAngle(ChairRoundTop, 0.0F, 0.0F, 0.9075712110370513F);
        this.Spike_2 = new ModelRenderer(textureSize[0], textureSize[1], 14, 101);
        this.Spike_2.setRotationPoint(-0.5F, 1.5F, -1.5F);
        this.Spike_2.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.ChairArmPartFrontRight = new ModelRenderer(textureSize[0], textureSize[1], 49, 0);
        this.ChairArmPartFrontRight.setRotationPoint(-1.0F, 1.0F, -1.0F);
        this.ChairArmPartFrontRight.addBox(0.0F, 0.0F, 0.0F, 1, 6, 7, 0.0F);
        this.WeaponTop = new ModelRenderer(textureSize[0], textureSize[1], 26, 47);
        this.WeaponTop.setRotationPoint(1.0F, 7.0F, 0.0F);
        this.WeaponTop.addBox(0.0F, 0.0F, 0.0F, 2, 2, 1, 0.0F);
        this.setRotateAngle(WeaponTop, 0.0F, 0.0F, 0.7853981633974483F);
        this.ChairFootHolder = new ModelRenderer(textureSize[0], textureSize[1], 0, 32);
        this.ChairFootHolder.setRotationPoint(0.0F, 2.0F, -2.5F);
        this.ChairFootHolder.addBox(0.0F, 0.0F, 0.0F, 10, 1, 3, 0.0F);
        this.Spike_4 = new ModelRenderer(textureSize[0], textureSize[1], 28, 101);
        this.Spike_4.setRotationPoint(-0.5F, 2.7F, -1.5F);
        this.Spike_4.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.CrownSpike_5 = new ModelRenderer(textureSize[0], textureSize[1], 10, 0);
        this.CrownSpike_5.setRotationPoint(0.0F, -1.0F, 4.0F);
        this.CrownSpike_5.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.ChairRoundMidLeft = new ModelRenderer(textureSize[0], textureSize[1], 9, 82);
        this.ChairRoundMidLeft.setRotationPoint(0.0F, 10.0F, 0.0F);
        this.ChairRoundMidLeft.addBox(0.0F, 0.0F, -2.0F, 2, 7, 2, 0.0F);
        this.setRotateAngle(ChairRoundMidLeft, 0.0F, 0.0F, -0.5235987755982988F);
        this.HumanLowerBody = new ModelRenderer(textureSize[0], textureSize[1], 50, 57);
        this.HumanLowerBody.setRotationPoint(0.0F, 4.0F, 0.0F);
        this.HumanLowerBody.addBox(-2.0F, 0.0F, -2.0F, 4, 3, 2, 0.0F);
        this.setRotateAngle(HumanLowerBody, -0.3141592653589793F, 0.0F, 0.0F);
        this.Spike_3 = new ModelRenderer(textureSize[0], textureSize[1], 21, 101);
        this.Spike_3.setRotationPoint(-0.5F, 5.8F, -1.5F);
        this.Spike_3.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.WeaponBladeLeft = new ModelRenderer(textureSize[0], textureSize[1], 38, 32);
        this.WeaponBladeLeft.setRotationPoint(2.0F, 0.0F, 0.0F);
        this.WeaponBladeLeft.addBox(0.0F, 0.0F, 0.0F, 1, 7, 1, 0.0F);
        this.setRotateAngle(WeaponBladeLeft, 0.0F, 0.0F, 2.295107966372543F);
        this.CrownSpike_3 = new ModelRenderer(textureSize[0], textureSize[1], 5, 3);
        this.CrownSpike_3.setRotationPoint(0.0F, -1.0F, 2.0F);
        this.CrownSpike_3.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.Spike_5 = new ModelRenderer(textureSize[0], textureSize[1], 35, 101);
        this.Spike_5.setRotationPoint(-0.6F, 1.2F, -1.5F);
        this.Spike_5.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.setRotateAngle(Spike_5, 0.0F, 0.0F, -0.4363323129985824F);
        this.HumanUpperArmRight = new ModelRenderer(textureSize[0], textureSize[1], 41, 50);
        this.HumanUpperArmRight.setRotationPoint(-2.0F, 0.5F, -1.0F);
        this.HumanUpperArmRight.addBox(-2.0F, 0.0F, -1.0F, 2, 4, 2, 0.0F);
        this.setRotateAngle(HumanUpperArmRight, -0.3490658503988659F, 0.0F, 0.3490658503988659F);
        this.Spike_7 = new ModelRenderer(textureSize[0], textureSize[1], 77, 101);
        this.Spike_7.setRotationPoint(-1.5F, 2.5F, -1.5F);
        this.Spike_7.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.ChairBackRight_1 = new ModelRenderer(textureSize[0], textureSize[1], 0, 56);
        this.ChairBackRight_1.setRotationPoint(9.9F, -15.0F, -1.0F);
        this.ChairBackRight_1.addBox(0.0F, 0.0F, 0.0F, 2, 11, 1, 0.0F);
        this.Spike_8 = new ModelRenderer(textureSize[0], textureSize[1], 70, 101);
        this.Spike_8.setRotationPoint(-1.5F, 7.0F, -1.5F);
        this.Spike_8.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1, 0.0F);
        this.ChairRoundTopRight = new ModelRenderer(textureSize[0], textureSize[1], 0, 92);
        this.ChairRoundTopRight.setRotationPoint(0.0F, 7.0F, 0.0F);
        this.ChairRoundTopRight.addBox(-2.0F, 0.0F, -2.0F, 2, 6, 2, 0.0F);
        this.setRotateAngle(ChairRoundTopRight, 0.0F, 0.0F, 0.4886921905584123F);
        this.CrownLeft = new ModelRenderer(textureSize[0], textureSize[1], 0, 115);
        this.CrownLeft.setRotationPoint(4.0F, 0.0F, 1.0F);
        this.CrownLeft.addBox(0.0F, 0.0F, 0.0F, 1, 2, 4, 0.0F);
        this.CrownSpike_6 = new ModelRenderer(textureSize[0], textureSize[1], 0, 6);
        this.CrownSpike_6.setRotationPoint(4.0F, -1.0F, 4.0F);
        this.CrownSpike_6.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.CrownMain.addChild(this.CrownLeftSpike);
        this.Base.addChild(this.ChairBase);
        this.Base.addChild(this.HumanUpperBody);
        this.WeaponHandProtection.addChild(this.WeaponBlade);
        this.CrownFront.addChild(this.CrownSpike_1);
        this.ChairRoundBottomRight.addChild(this.Spike_1);
        this.WeaponTop.addChild(this.WeaponBladeRight);
        this.ChairFootHolder.addChild(this.CrownMain);
        this.HumanLowerBody.addChild(this.HumanUpperLegLeft);
        this.CrownFront.addChild(this.CrownBack);
        this.CrownFront.addChild(this.CrownSpike_2);
        this.CrownRightSpike.addChild(this.CrownGem_2);
        this.ChairBack.addChild(this.ChairBackTop);
        this.HumanUpperLegRight.addChild(this.HumanLowerLegRight);
        this.CrownFront.addChild(this.CrownSpike_7);
        this.ChairArmPartLeft.addChild(this.ChairSupportLeft);
        this.CrownFront.addChild(this.CrownSpike);
        this.ChairArmPartLeft.addChild(this.ChairArmPartFrontLeft);
        this.CrownRightSpike.addChild(this.CrownGem);
        this.HumanLowerBody.addChild(this.HumanUpperLegRight);
        this.ChairBase.addChild(this.ChairRoundBottomLeft);
        this.ChairRoundTop.addChild(this.Spike_6);
        this.HumanUpperBody.addChild(this.HumanUpperArmLeft);
        this.ChairRoundMidLeft.addChild(this.ChairRoundTopLeft);
        this.ChairArmPartRight.addChild(this.ChairSupportRight_1);
        this.CrownMain.addChild(this.CrownMidSpike);
        this.ChairRoundMidLeft.addChild(this.Spike_10);
        this.HumanUpperLegLeft.addChild(this.HumanLowerLegLeft);
        this.ChairArmPartRight.addChild(this.ChairSupportRight);
        this.HumanUpperArmRight.addChild(this.HumanUpperArmRight_1);
        this.Head.addChild(this.CrownFront);
        this.ChairRoundMidLeft.addChild(this.Spike_9);
        this.ChairBase.addChild(this.ChairBack);
        this.ChairRoundTopLeft.addChild(this.Spike_11);
        this.WeaponGrip.addChild(this.WeaponHandProtection);
        this.ChairBack.addChild(this.ChairBackRight);
        this.ChairBase.addChild(this.ChairRoundBottomRight);
        this.ChairBase.addChild(this.ChairArmPartLeft);
        this.CrownFront.addChild(this.CrownRight);
        this.ChairArmPartRight.addChild(this.WeaponGrip);
        this.HumanUpperArmLeft.addChild(this.HumanUpperArmLeft_1);
        this.ChairRoundBottomRight.addChild(this.ChairRoundMidRight);
        this.ChairRoundBottomRight.addChild(this.Spike);
        this.HumanUpperBody.addChild(this.Head);
        this.ChairBase.addChild(this.ChairArmPartRight);
        this.CrownRightSpike.addChild(this.CrownGem_1);
        this.CrownMain.addChild(this.CrownRightSpike);
        this.ChairArmPartLeft.addChild(this.ChairSupportLeft_1);
        this.CrownFront.addChild(this.CrownSpike_4);
        this.ChairRoundTopRight.addChild(this.ChairRoundTop);
        this.ChairRoundMidRight.addChild(this.Spike_2);
        this.ChairArmPartRight.addChild(this.ChairArmPartFrontRight);
        this.WeaponBlade.addChild(this.WeaponTop);
        this.ChairBase.addChild(this.ChairFootHolder);
        this.ChairRoundTopRight.addChild(this.Spike_4);
        this.CrownFront.addChild(this.CrownSpike_5);
        this.ChairRoundBottomLeft.addChild(this.ChairRoundMidLeft);
        this.HumanUpperBody.addChild(this.HumanLowerBody);
        this.ChairRoundMidRight.addChild(this.Spike_3);
        this.WeaponTop.addChild(this.WeaponBladeLeft);
        this.CrownFront.addChild(this.CrownSpike_3);
        this.ChairRoundTop.addChild(this.Spike_5);
        this.HumanUpperBody.addChild(this.HumanUpperArmRight);
        this.ChairRoundBottomLeft.addChild(this.Spike_7);
        this.ChairBack.addChild(this.ChairBackRight_1);
        this.ChairRoundBottomLeft.addChild(this.Spike_8);
        this.ChairRoundMidRight.addChild(this.ChairRoundTopRight);
        this.CrownFront.addChild(this.CrownLeft);
        this.CrownFront.addChild(this.CrownSpike_6);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z)
    {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
